import os
import subprocess

from shellwrapper import BaseShellCommand


class LibreOfficeShellCommand(BaseShellCommand):
    """
    Command to render office files to PDF.
    """

    def __init__(self, office_file, logger=None):
        self.office_file = office_file

        super(LibreOfficeShellCommand, self).__init__(["libreoffice", "soffice"], logger)

    def execute(self):
        """
        Execute the command.
        """
        args = [
            "--headless",
            "--convert-to", "pdf",
            self.office_file,
            "--outdir", self.temp_directory]

        return self._execute_command(args)

    @property
    def pdf_file(self):
        """
        Retrieves the list of absolute paths to image files generated by this command in sort order.
        """
        pdf_name = os.path.splitext(os.path.basename(self.office_file))[0] + ".pdf"
        return os.path.abspath(os.path.join(self.temp_directory, pdf_name))