import os

from shellwrapper import BaseShellCommand


class MuDrawShellCommand(BaseShellCommand):
    """
    Command to render a PDF to individual image files.
    """

    def __init__(self, pdf_file, resolution_dpi, page_file_format="page%03d.png", logger=None):
        self.pdf_file = pdf_file
        self.resolution_dpi = resolution_dpi
        self.page_image_file_format = page_file_format

        super(MuDrawShellCommand, self).__init__(["pdfdraw", "mudraw"], logger)

    def execute(self):
        """
        Execute the command.
        """
        args = [
            "-r", str(self.resolution_dpi),
            "-o", os.path.join(self.temp_directory, self.page_image_file_format),
            self.pdf_file]

        return self._execute_command(args)

    @property
    def page_image_files(self):
        """
        Retrieves the list of absolute paths to image files generated by this command in sort order.
        """
        image_files = [os.path.abspath(os.path.join(self.temp_directory, p)) for p in os.listdir(self.temp_directory)]
        image_files.sort()
        return image_files